services:
  - type: cron
    name: smbot-cron
    env: python
    schedule: "50 3 * * 1-5"  # 9:20 AM IST = 3:50 UTC Mon-Fri
    buildCommand: pip install -r requirements.txt
    startCommand: python src/run_bot.py
    envVars:
      - key: FY_ID
        sync: false
      - key: TOTP_KEY
        sync: false
      - key: PIN
        sync: false
      - key: APP_ID
        sync: false
      - key: SECRET_ID
        sync: false
      - key: REDIRECT_URI
        sync: false